[workspace]
members = [
    "styks-cli",
    "styks-contracts",
]
resolver = "2"

[workspace.dependencies]
odra = { version = "2.2.0", features = [], default-features = false }
odra-test = { version = "2.2.0", features = [], default-features = false }
odra-build = { version = "2.2.0", features = [], default-features = false }
odra-cli = { version = "2.2.0", features = [], default-features = false }
odra-modules = { version = "2.2.0", features = [], default-features = false }

[profile.release]
codegen-units = 1
lto = true

[profile.dev.package."*"]
opt-level = 3
